module.exports = {
  country: 'canada',
  specialisation: 'cs',
  universities: [
    {
      name: 'University of Toronto',
      program: 'MEng Computer Science',
      duration: '1 year',
      location: 'Toronto, Ontario',
      ranking: 18,
      tuition: { annualLocal: 42000, localCurrency: 'CAD', annualINR: 2604000, totalINR: 2604000 },
      requirements: { cgpaCutoff: 7.5, greRequired: true, greMinScore: 310, ieltsMin: 6.5, toeflMin: 93 },
      deadlines: { fall: 'December 1', winter: null },
      applicationUrl: 'https://www.sgs.utoronto.ca',
    },
    {
      name: 'University of British Columbia',
      program: 'MSc Computer Science',
      duration: '2 years',
      location: 'Vancouver, BC',
      ranking: 34,
      tuition: { annualLocal: 38000, localCurrency: 'CAD', annualINR: 2356000, totalINR: 4712000 },
      requirements: { cgpaCutoff: 7.0, greRequired: false, greMinScore: null, ieltsMin: 6.5, toeflMin: 90 },
      deadlines: { fall: 'December 15', winter: null },
      applicationUrl: 'https://www.cs.ubc.ca/graduate',
    },
    {
      name: 'McGill University',
      program: 'MSc Computer Science',
      duration: '2 years',
      location: 'Montreal, Quebec',
      ranking: 46,
      tuition: { annualLocal: 22000, localCurrency: 'CAD', annualINR: 1364000, totalINR: 2728000 },
      requirements: { cgpaCutoff: 7.5, greRequired: false, greMinScore: null, ieltsMin: 6.5, toeflMin: 90 },
      deadlines: { fall: 'January 15', winter: null },
      applicationUrl: 'https://www.cs.mcgill.ca/graduate',
    },
    {
      name: 'University of Waterloo',
      program: 'MMath Computer Science',
      duration: '2 years',
      location: 'Waterloo, Ontario',
      ranking: 149,
      tuition: { annualLocal: 18000, localCurrency: 'CAD', annualINR: 1116000, totalINR: 2232000 },
      requirements: { cgpaCutoff: 7.8, greRequired: false, greMinScore: null, ieltsMin: 7.0, toeflMin: 93 },
      deadlines: { fall: 'December 1', winter: 'April 1' },
      applicationUrl: 'https://cs.uwaterloo.ca/graduate',
    },
    {
      name: 'University of Alberta',
      program: 'MSc Computing Science',
      duration: '2 years',
      location: 'Edmonton, Alberta',
      ranking: 111,
      tuition: { annualLocal: 14000, localCurrency: 'CAD', annualINR: 868000, totalINR: 1736000 },
      requirements: { cgpaCutoff: 6.5, greRequired: false, greMinScore: null, ieltsMin: 6.5, toeflMin: 90 },
      deadlines: { fall: 'January 15', winter: null },
      applicationUrl: 'https://www.ualberta.ca/computing-science/graduate-studies',
    },
  ],
  visa: {
    type: 'Canadian Student Visa (Study Permit)',
    processingTime: '8-12 weeks',
    fees: { localAmount: 150, localCurrency: 'CAD', INR: 9300 },
    financialProof: 'CAD 10,000 per year above tuition fees',
    steps: [
      'Receive offer letter from university',
      'Create GCKey or Sign-In Canada account on IRCC portal',
      'Complete online Study Permit application',
      'Upload all required documents',
      'Pay application fee of CAD 150',
      'Provide biometrics at a VAC if required (CAD 85)',
      'Receive Port of Entry (POE) letter',
      'Get Study Permit stamped at Canadian port of entry',
    ],
    officialUrl: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html',
  },
  costs: {
    tuition: { annualMinINR: 1100000, annualMaxINR: 2700000 },
    living: [
      { city: 'Toronto', monthlyINR: 120000, annualINR: 1440000 },
      { city: 'Vancouver', monthlyINR: 115000, annualINR: 1380000 },
      { city: 'Montreal', monthlyINR: 90000, annualINR: 1080000 },
      { city: 'Waterloo', monthlyINR: 80000, annualINR: 960000 },
      { city: 'Edmonton', monthlyINR: 75000, annualINR: 900000 },
    ],
    otherOneTime: { visaFeesINR: 9300, healthInsuranceINR: 40000, flightAndSetupINR: 120000 },
  },
  postStudy: {
    workPermit: {
      name: 'Post-Graduation Work Permit (PGWP)',
      duration: 'Up to 3 years (equal to program length)',
      eligibility: 'Must graduate from a PGWP-eligible Designated Learning Institution (DLI)',
      applicationWindow: 'Apply within 180 days of receiving final marks',
    },
    prPathway: {
      name: 'Express Entry — Canadian Experience Class (CEC)',
      description: 'After 1 year of skilled work experience in Canada on PGWP, you become eligible for PR through Express Entry CEC stream',
      typicalTimeline: '2-3 years after graduation',
    },
    averageSalaryCAD: 75000,
    averageSalaryINR: 4650000,
  },
  timeline: [
    { monthsFromNow: -18, milestone: 'Start GRE preparation', category: 'exam', details: 'Target 315+ for top Canadian universities. Many Canadian universities do not require GRE but U of T MEng does.' },
    { monthsFromNow: -14, milestone: 'Give IELTS or TOEFL', category: 'exam', details: 'Book slot 2 months in advance. Target IELTS 7.0+ or TOEFL 100+.' },
    { monthsFromNow: -12, milestone: 'Research and shortlist universities', category: 'research', details: 'Aim for 2 reach, 3 match, 2 safe schools based on your profile.' },
    { monthsFromNow: -10, milestone: 'Request transcripts and LORs', category: 'documents', details: 'Approach professors and managers early. Give them at least 4 weeks.' },
    { monthsFromNow: -8, milestone: 'Write SOP and CV', category: 'application', details: 'Tailor your SOP to each university and program. Highlight research and projects.' },
    { monthsFromNow: -6, milestone: 'Submit applications', category: 'application', details: 'Most Canadian Fall deadlines are December–January. Do not miss them.' },
    { monthsFromNow: -4, milestone: 'Receive offer letters', category: 'decision', details: 'Compare funding packages, location, co-op opportunities, and placement stats.' },
    { monthsFromNow: -3, milestone: 'Accept offer and pay deposit', category: 'decision', details: 'Typically CAD 1,000–3,000 acceptance deposit required.' },
    { monthsFromNow: -2, milestone: 'Apply for Study Permit', category: 'visa', details: 'Apply on IRCC portal immediately after receiving offer letter. Processing is 8-12 weeks.' },
    { monthsFromNow: -1, milestone: 'Book flights and accommodation', category: 'visa', details: 'Look for on-campus housing first. Book early — fills up fast for Fall intake.' },
  ],
  documents: {
    academic: [
      'Official transcripts from all 8 semesters (sealed)',
      'Degree certificate or provisional passing certificate',
      'Consolidated mark sheet',
      'Medium of instruction certificate (if applicable)',
    ],
    testScores: [
      'GRE scorecard (if required by university — send official scores)',
      'IELTS Test Report Form or TOEFL score report',
      'Official scores must be sent directly from ETS/British Council to universities',
    ],
    application: [
      'Statement of Purpose (800–1200 words, tailored per university)',
      '3 Letters of Recommendation (2 academic + 1 professional preferred)',
      'Updated CV / Resume (2 pages max)',
      'Completed online application form per university',
      'Application fee payment (CAD 100–200 per university)',
    ],
    visa: [
      'Valid Indian passport (min 6 months validity beyond program end date)',
      'Offer/Acceptance letter from university',
      'Proof of financial support (bank statements showing 6 months history)',
      'Fixed deposit receipts or education loan sanction letter',
      'Sponsor letter if parents are funding (with their income proof)',
      '2 recent passport size photographs',
      'Completed IMM 1294 application form',
      'Biometrics at a Visa Application Centre (if required)',
    ],
  },
};
